services:
  server:
    build: server
    environment:
      POSTGRES_HOSTNAME: database
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DBNAME: vocab
      MISTRAL_API_KEY: ${MISTRAL_API_KEY?}
    ports:
      - 80
    restart: always
    labels:
      - webproxy.path=vocab
    depends_on:
      - database
    develop:
      watch:
        - action: rebuild
          path: server
  database:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vocab
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
#     - ./database/sample.sql:/docker-entrypoint-initdb.d/sample.sql:ro
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database_data:
